### ISSUE TITLE
Duplicated classes on Drawer items

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-component-library#216]
#### Describe the bug
Some classes are being added multiple times to the Drawer Item titles

#### What is the expected behavior?
Classes should only be applied once without duplication

#### What are the steps to reproduce?
1. Launch the showcase demo
2. Inspect the title of an item in the Nav Drawer (the span)
3. Observe all of the classes are there twice (or more)

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/103919310-e41c8180-50dd-11eb-849c-15950541d72c.png)

		
#### Anything else to add?
I messed with this for a minute and couldn't figure it out. The props coming in to the NavItem seem to only have them listed once, but idk. Weird.

**Comment by emclaug2** [comment]
@joebochill might fix this as part of the refactor story.

**Comment by joebochill** [comment]
I came cross an issue on MUI that seemed to indicate that this might be a problem on their end (that they say is fixed in v5) related to nested style rules in JSS that depend on props. I can't seem to find that issue now, but if I do I will link it.

**Comment by joebochill** [comment]
Let's see if this is fixed after we move to v5.

**Comment by emclaug2** [comment]
We're now on MUI5; if this issue isn't needed it can be closed.

**Comment by joebochill** [comment]
Need to assign somebody to check this.

**Comment by daileytj** [comment]
These classes are still being duplicated

**Comment by joebochill** [comment]
This only seems to be an issue with the InfoListItem / DrawerNavItem. I thought it might have something to do with the ListItemButton conditional wrapper for clickable items, but removing that still shows some duplicated classes (e.g., BLUIDrawerNavItem-title).

**Comment by joebochill** [comment]
The issue is in our use of the `combine` function. It combines the `defaultClasses[xxx]` with `classes[xxx]`, but `defaultClasses` already accounts for the classes prop.

<img width="849" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/29152776/6ab5e03b-f672-44a6-a79b-8f8fee8b43b8">
<img width="790" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/29152776/8c6f0943-aaf8-44f9-8c51-9ba43e02ddaf">

This is a problem in every component...we're just seeing it in the DrawerNavItem because it's the only place where we have actually used the `classes` prop for one of our components.

Confirmed this by using `classes` on the ChannelValue demo:
<img width="774" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/29152776/b529d160-0e5c-4915-b101-b23accb5e44c">
![image](https://github.com/etn-ccis/blui-react-component-library/assets/29152776/cede7460-8986-46a1-bd1a-89e2cbd7063e)


The fix is to stop using the `combine` function since it is unnecessary.

```diff
<Component 
-   className={combine('xxx')} 
+   className={defaultClasses['xxx']}
/>


```
