### ISSUE TITLE
Componentize the examples page

### ISSUE THREAD

**Issue by bkarambe** [etn-ccis/blui-react-component-library#508]
#### Describe the bug
There are some duplicate styles applied to example page wrapper

#### What is the expected behavior?
Componentize the example wrapper to use the duplicate styles

#### What are the steps to reproduce?
1. yarn start:reactdev

#### Anything else to add?
https://github.com/brightlayer-ui/react-component-library/pull/502#issuecomment-1239672805

**Comment by ektasawant** [comment]
Link this issue to cleanup story.

**Comment by huayunh** [comment]
Created as BLUI-3508

**Comment by surajeaton** [comment]
I checked it. This has already been fixed. @daileytj Can you please re-verify?
