### ISSUE TITLE
App Bar animationDuration prop not expanding app bar when set to 1000ms

### ISSUE THREAD

**Issue by ektasawant** [etn-ccis/blui-react-component-library#515]
#### Describe the bug
App Bar `animationDuration` prop not expanding the app bar when set to 1000ms.
#### What is the expected behavior?
App Bar `animationDuration` prop should expand the app bar when set to 1000ms. 
#### What are the steps to reproduce?
1. Go to dev docs `/components/app-bar/playground`
2. set animationDuration to 1000ms
3. scroll window app bar is not expanding.(This is inconsistent )

#### Environment

All browsers	
#### Anything else to add?
https://github.com/brightlayer-ui/react-component-library/pull/511#issuecomment-1241330853
https://github.com/brightlayer-ui/react-component-library/pull/511#issuecomment-1243547676

Issue is related to Component Library.

**Comment by joebochill** [comment]
The 1000ms part of this issue is irrelevant now. Closing this and creating a new issue to track the inconsistent collapse/expand behavior described above: https://github.com/etn-ccis/blui-react-component-library/issues/736
