### ISSUE TITLE
Chaotic naming conventions for drawer rail itemc API documentation

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#548]
## Describe the bug

in our API table, this thing is referred by different names, therefore potentially confusing our users.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/8997218/192007746-063923af-6238-41de-b7c7-b66f827baaab.png">

## What is the expected behavior?

They should be consistently called `title` or `title text`

## Additional issue

the `icon` prop is described to be "A component to render for the **left** icon". There's no "left" icon — probably a copy-paste error.

**Comment by bkarambe** [comment]
<img width="1792" alt="Screenshot 2022-10-06 at 6 29 10 PM" src="https://user-images.githubusercontent.com/25982779/194319157-11bff01b-5564-4a8a-93ca-46127894522a.png">

**Comment by bkarambe** [comment]
We need to fix **title**.
