### ISSUE TITLE
dev doc example code snippets indent displaying with extra space

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-react-component-library#566]
#### Describe the bug
When viewing the first (top) example the example code snippet looks correct with indenting. When you view the remaining example code snippets they have extra indenting unlike the first (top) one.
#### What is the expected behavior?
indenting (code formatting to be the same)
#### What are the steps to reproduce?
1. Go to any component example....
2. view any code snippet

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/193287220-f746bd67-4cd4-4971-a304-3c9b29a0afa4.png)
![image](https://user-images.githubusercontent.com/37150565/193287291-1fd028a1-4352-4e97-887c-e2ee4828c6dd.png)
![image](https://user-images.githubusercontent.com/37150565/193287967-c711d82b-9a93-41bc-832f-2d00036c439e.png)
![image](https://user-images.githubusercontent.com/37150565/193288084-710ef8d8-06b0-4604-a1f7-ba6ad81404a0.png)

**Comment by JeffGreiner-eaton** [comment]
reviewed all the example code snippets and this isn't an issue and has been fixed
