### ISSUE TITLE
Dev Doc drawer examples page, temporary drawer prevents scrolling

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#614]
#### What are the steps to reproduce?
1. Go to [dev doc drawer examples page](https://brightlayer-ui-components.github.io/react-dev/components/drawer/examples), under Temporary Variant
2. Click on hamburger menu to open the temp drawer
3. now try to click or scroll anywhere else 
4. Observe that all interactions are blocked, unless you click the "x" again

#### What is the expected behavior?

Users should be able to interact freely with anything outside the gray "example" zone.

**Comment by jeffvg** [comment]
was looking at this and MUI example does has the same behavior here. https://mui.com/material-ui/react-drawer/#temporary-drawer

Tried using disableScrollLock={true} in the example and allows scroll but overflows on app header
