### ISSUE TITLE
Yeet storybook

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#758]
## Describe the desired feature/functionality

The code in `/demos/storybook/` is no longer in use. Consider removing it.

## Additional Context (where / how would this be used)

Also remember to clean up other places, including:
- CI/CD
- Package.json
- Readme (contributor guide)

## Suggested implementation details

```
rm -rf
```

**Comment by JeffGreiner-eaton** [comment]
Ditto on angular comp lib as well
