### ISSUE TITLE
Duplicate props shown in the List Item Tag playground code snippet

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#768]
#### Describe the bug / expected behavior

On List Item Tag's playground page, there is a duplicate prop `backgroundColor` that should have been `fontColor` instead.

## What are the steps to reproduce?

1. Go to https://brightlayer-ui-components.github.io/react/components/list-item-tag/playground
2. Observe that there are two `backgroundColor` prop being shown in the code snippet area at the bottom of the screen.

## Screenshots / Screen recording

![image](https://user-images.githubusercontent.com/8997218/234763633-4cf201d2-e910-4a0e-a5be-474cee149153.png)

#### Your environment information

Chrome, MacOS

## Suggested fix

https://github.com/etn-ccis/blui-react-component-library/blob/db563fc5664f3fdb5295128b37a7c13ce3a9e06a/docs/src/componentDocs/ListItemTag/playground/PreviewComponent.tsx#L20

This line, replace all `backgroundColor` with `fontColor` should do the trick.

## Anything else to add?

Please leave this for someone new to React or new to this project to fix.

**Comment by joebochill** [comment]
Fixed in the migration to shared tooling
