### ISSUE TITLE
Add Blockquote Component

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-component-library#773]
#### Describe the desired feature/functionality
Add a blockquote component
![Screen Shot 2023-05-10 at 7 48 29 AM](https://github.com/etn-ccis/blui-react-component-library/assets/13989985/36a834a7-76ab-4f5b-8223-0e09514e861c)

#### Additional Context (where / how would this be used)
This is an adopter request, but we are already using something similar to this on the documentation site. The implementation in the current doc site is using global blockquote styles instead of a reusable component.

#### Suggested implementation details

API Proposal:
```tsx
type BluiBlockquoteProps = {
    color: string // the color for the leftBorder and backgroundColor(opacity 0.1 will be applied to backgroundColor)
    content: string // text to render inside the blockquote component
    leftBorderColor?: // color of the leftBorder (default: theme.primary.main)
    backgroundColor?: // color of the background (default: theme.primary.main w/ opacity 0.1)
}
```

**Comment by huayunh** [comment]
note that React Dev Doc is currently [using a different style](https://brightlayer-ui-components.github.io/react-dev/getting-started/environment):

<img width="911" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/8997218/8ff701f9-84db-47f4-b4f5-25e1451ef0af">

This is influenced by how much the author needs to emphasize something to their readers.

**Comment by huayunh** [comment]
Blockquote contents shall just be the children of the component, and shall take ReacNode so that anything can be rendered (such as HTML tags like `<code>`)

**Comment by huayunh** [comment]
And this may be better grouped with all those playground components, under a new package like `@brightlayer-ui/react-docs`

**Comment by joebochill** [comment]
I haven't heard a strong enough demand from adopters to justify building this as a component for all teams. It seems simple enough for them to implement their own div with a stripe on the side and some text inside.
