### ISSUE TITLE
The playground component preview for the drawer component is not rendering on mobile

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#806]
#### Describe the bug / expected behavior

In the playground of the `<Drawer>` component, nothing is rendered when the viewport is mobile-sized.

#### What are the steps to reproduce?

1. Go to https://brightlayer-ui-components.github.io/react-dev/components/drawer/playground
2. Observe that the drawer is behaving OK on desktop, but not on mobile sizes

#### Screenshots / Screen recording

This is supposed to be an `open` `permanent` drawer:

<img width="379" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/8997218/bddda1af-6590-4cd2-a919-ddffc3b8684f">

#### Suggested fix

This is likely due to the drawer's parent container being shrunk to 0px on mobile due to the use of an fixed size margin:

<img width="364" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/8997218/4693dd1b-3d21-426d-907a-27666e2bcf4d">

**Comment by joebochill** [comment]
It doesn't look like a margin issue, but rather a calculated size which eventually goes negative:
<img width="319" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/29152776/50401d05-e443-4a9a-9b60-4daa22fb8153">

**Comment by huayunh** [comment]
https://github.com/etn-ccis/blui-react-component-library/blob/1c4ccb2f00cb9fedc9b45556bbcfdcd04ba3ae24/docs/src/componentDocs/Drawer/playground/PlaygroundPage.tsx#L249

**Comment by joebochill** [comment]
Reopening as the proposed fix breaks the expected Drawer behavior:
https://github.com/etn-ccis/blui-react-component-library/assets/29152776/b9fa60b5-02ff-454b-9975-6582efab0ab1
