### ISSUE TITLE
lonely `>` on a new line when not necessary

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#830]
## Describe the desired feature/functionality

Just a small feature request. I would understand if we choose to mark this as `wont-fix`. 

A few generated code snippet shows the closing `>` on a new line when no props are present, making my `prettier` head twitch. This is drawer subheader's playground, with its default configuration:
![image](https://github.com/etn-ccis/blui-react-component-library/assets/8997218/3220d5af-20db-44e2-9449-5afc09b8d97f)

## Suggested implementation details
When no prop is present, the `>` shall be on the same line as the component name.

**Comment by surajeaton** [comment]
Please refer to AppBar playground utility function.
https://brightlayer-ui-components.github.io/react-dev/components/app-bar/playground
