### ISSUE TITLE
Empty State dev doc playground, `icon={<Router ... />}` does not get rendered correctly

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#831]
#### Describe the bug / expected behavior

Empty state, selecting `<Router>` for the `icon` prop will cause the icon to disappear.

`<Router>` exists as a MUI Icon and a Material Design icon.

#### What are the steps to reproduce?

1. Go to https://brightlayer-ui-components.github.io/react-dev/components/empty-state/playground
2. set the `icon` prop to `<Router />` in the dropdown on the right

#### Screenshots / Screen recording

![image](https://github.com/etn-ccis/blui-react-component-library/assets/8997218/0824e905-6c4e-431f-b7b9-95582a56c126)

**Comment by surajeaton** [comment]
Add Router icon to  icon lookup function.
