### ISSUE TITLE
Update drawerRailItem to use SharedStyleProps only

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-react-component-library#861]
#### Describe the bug / expected behavior
The docs incorrectly state that the DrawerRailItem supports sharedProps — it does not support all of the styles that are listed there....it only supports a subset of them. In the docs, we're showing both SharedStyleProps & NavItemSharedStyleProps as the shared props. DrawerRailItem only supports the SharedStyleProps.
In the playground component, we are showing inputs/knobs for those props that are not supported and they are being spread down to the DrawerRailItem, which doesn't know what they are.

We have set a filter in the drawer rail Item playground here to clear the console warnings.
https://github.com/etn-ccis/blui-react-component-library/blob/b6dae00bda5bb14071a0cada2a699509a36d205c/docs/src/componentDocs/DrawerRailItem/playground/PlaygroundPage.tsx#L81

#### What are the steps to reproduce?

1. Go to...
2. Click on...

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by ArshdeepSingh3-eaton** [comment]
[fixed and merged](https://github.com/etn-ccis/blui-react-component-library/pull/904)
