### ISSUE TITLE
Google Analytics Wrapper Send command doesn't exist warning

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-react-component-library#862]
#### Describe the bug / expected behavior
The warning is seen in dev tools for this repo and other repos where google analytics is sending data. Investigate why the send command no longer works and fix the issue.

![image](https://github.com/etn-ccis/blui-react-component-library/assets/119693939/19cca0ee-3df9-41ee-9cb9-4396bca4e24d)

#### What are the steps to reproduce?

1. Go to https://brightlayer-ui-components.github.io/react/components/app-bar/examples
2. Open dev tools
3. view warning

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by huayunh** [comment]
Dup issue with https://github.com/etn-ccis/blui-react-component-library/issues/777
