### ISSUE TITLE
Incorrect prop type in Toolbar Menu

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-component-library#871]
#### Describe the bug / expected behavior
Incorrect `items` prop type in Toolbar Menu Groups Object

#### What are the steps to reproduce?

1. [Go to...](https://brightlayer-ui-components.github.io/react/components/toolbar-menu/api-docs)
2. Scroll down to Toolbar Menu Groups Object
3. The `items` prop has incorrect type and no link to the reference

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2024-04-10 at 4 52 11 PM" src="https://github.com/etn-ccis/blui-react-component-library/assets/120575281/5d0cc4c9-4207-4695-a95e-c6e0ba382ec4">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix
Update the type to `ToolbarMenuCompItem` and add a link to https://github.com/etn-ccis/blui-react-component-library/blob/2fb920025a3bbe424c1892b502de7ebbffad702d/components/src/core/ToolbarMenu/ToolbarMenu.tsx#L34

**Comment by huayunh** [comment]
So why is "tool bar menu object" still listed in this screenshot? Why do we go with a vague name like `ToolbarMenuCompItem`?

![image](https://github.com/etn-ccis/blui-react-component-library/assets/8997218/eb35c91c-1d36-4a9f-b570-d145ae9510f4)

**Comment by ektaghag-eaton** [comment]
Leave ToolbarMenuCompItem as it is and new ToolbarMenuItem like 
`export type ToolbarMenuItem = ToolbarMenuCompItem`

We should use the type ToolbarMenuItem in our code.

**Comment by manojleaton** [comment]
Issue is fixed in this [PR](https://github.com/etn-ccis/blui-react-component-library/pull/906/files)

**Comment by manojleaton** [comment]
Issue is fixed with this [PR](https://github.com/etn-ccis/blui-react-component-library/pull/906/files)
