### ISSUE TITLE
mdx-js version(s) 3 breaks dev doc build

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-react-component-library#878]
#### Describe the bug / expected behavior
This was found during a dependency update PR. https://github.com/etn-ccis/blui-react-component-library/pull/876
Not sure if this should be a bug or more of enhancement

The update was updating mdx-js/loader to version 3.0.1 and this alone was breaking change. I tested with updating the other mdx-js packages but it continued breaking other items in theme demos. At the moment not sure if its just a compatibility issue with react or other packages.

<img width="515" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/119693939/6ac68956-e7cb-4ef6-9c71-cf16e6bbadc3">
<img width="531" alt="image" src="https://github.com/etn-ccis/blui-react-component-library/assets/119693939/7fc59ad2-41f3-4b80-bb9c-178ced778676">

Locally I tested using these versions:
"@mdx-js/loader": "^3.0.1",
"@mdx-js/mdx": "^3.0.1",
"@mdx-js/react": "^3.0.1",

#### What are the steps to reproduce?

1. Go to...
2. Click on...

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by ektaghag-eaton** [comment]
React native Dev Docs is using `"@mdx-js/loader": "^3.0.1"` and Vite. We can use the same configurations for React dev docs.
